backend:
  name: git-gateway
  branch: master

media_folder: "/assets/img" # Folder where user uploaded files should go
public_folder: "/assets/img"

collections: # A list of collections the CMS should be able to edit
  - label: "Home"
    name: "home"
    format: "json"
    files:
      - label: "Menu"
        name: "menu"
        file: "_data/menu.json"
        fields:
          - {label: Title, name: title, widget: string, hint: "The title"}
          - label: "categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: name, name: name, widget: string}