backend:
  name: git-gateway
  branch: master

media_folder: "/assets/img" # Folder where user uploaded files should go
public_folder: "/assets/img"

collections: # A list of collections the CMS should be able to edit
  - label: "Home"
    name: "home"
    format: "json"
    files:
      - label: "Hero content"
        name: "hero-content"
        file: "_data/hero.json"
        fields:
          - {label: Title, name: title, widget: string, hint: "The title"}
          - {label: Subtitle, name: subtitle, widget: string, hint: "The subtitle"}
          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Href, name: href, widget: string}
          - label: "Header Image"
            name: "image"
            widget: "object"
            fields:
              - {label: Src, name: src, widget: image}
      - label: "Image Gallery"
        name: "image-gallery"
        file: "_data/gallery.json"
        fields:
          - label: "Gallery Images"
            name: "image"
            widget: "list"
            field: {label: Image, name: image, widget: image}